chat/models.py
import datetime

from flask_login import UserMixin
from chat import db

from chat import login_manager


@login_manager.user_loader
def load_user(_id):
    return User.query.get(_id)


class User(db.Model, UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(120), nullable=False)
    last_name = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), default=datetime.datetime.utcnow)
    password = db.Column(db.String(50), nullable=False)

    sent = db.relationship('Message', foreign_keys="Message.sender_id", backref='user_sender', lazy=True,
                           cascade="all, delete-orphan")
    received = db.relationship('Message', foreign_keys="Message.recipient_id", backref='user_recipient', lazy=True,
                               cascade="all, delete-orphan")

    def __repr__(self):
        return "User( id: {}, first-name: {}, last-name: {}, email: {})".format(
            self.id, self.first_name, self.last_name, self.email
        )


class Message(db.Model):
    __tablename__ = "message"
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text, nullable=False)
    date_sent = db.Column(db.DateTime, default=datetime.datetime.utcnow, nullable=False)

    sender_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    recipient_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return "Message ( id: {}, sender_id: {}, recipient_id: {}, body: {}, sent date: {}".format(
            self.id, self.sender_id, self.recipient_id, self.body, self.date_sent
        )

chat/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_socketio import SocketIO
from flask_sqlalchemy import SQLAlchemy

socketio = SocketIO()

app = Flask(__name__)
app.config['SECRET_KEY'] = 'SOME_PRIVATE_KEY'
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"

db = SQLAlchemy()
db.init_app(app)
socketio.init_app(app)

login_manager = LoginManager(app)
bcrypt = Bcrypt(app)

from chat.main.routes import main as main_blueprint
from chat.auth.routes import auth as auth_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(auth_blueprint)

from .models import *

chat/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

chat/main/routes.py
from flask import redirect, url_for, render_template
from flask_login import login_required, current_user

from chat.models import User, Message
from . import main


@main.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    else:
        return redirect(url_for("Auth.login"))


@main.route('/chat/<int:user_id>')
def message(user_id: int):
    messages = Message.query.filter((Message.sender_id == current_user.id) & (Message.recipient_id == user_id) |
                                    (Message.recipient_id == current_user.id) & (Message.sender_id == user_id))

    context = {
        "recipient": user_id,
        "messages": messages
    }
    return render_template('chat.html', context=context)


@login_required
@main.route("/dashboard")
def dashboard():
    print("sssssss")
    if not current_user.is_authenticated:
        return redirect(url_for("Auth.login"))
    print(current_user)
    users = User.query.all()
    users = filter(lambda x: x.id != current_user.id, users)
    return render_template("dashboard.html", users=users)

chat/templates/chat.html
<html>
<head>
    <title>Flask-SocketIO-Chat: {{ room }}</title>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdn.socket.io/4.4.1/socket.io.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<script type="text/javascript" charset="utf-8">
            var socket;
            var _recipient = "{{ context.recipient }}"
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chatx');
                socket.on('connect', function() {
                    socket.emit('joined', { msg:_recipient  });
                });
                socket.on('message', function(data) {
                    var messageElement;

                    if(parseInt(data.recipient) == parseInt(_recipient)){
                        messageElement = sentMessageElement(data.msg);
                    }else{
                        messageElement = receivedMessageElement(data.msg);
                    }
                    const chatWindow = document.getElementById('chat-window');
                    chatWindow.appendChild(messageElement);

                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text, recipient:_recipient});
                    }
                });
            });

           function sentMessageElement(message) {
                  const messageContainer = document.createElement('div');
                  messageContainer.classList.add('flex', 'w-full', 'mt-2', 'space-x-3', 'max-w-xs', 'ml-auto', 'justify-end');

                  const messageContent = document.createElement('div');
                  messageContent.innerHTML = `
                    <div class="bg-blue-600 text-white p-3 rounded-l-lg rounded-br-lg">
                      <p class="text-sm">${message}</p>
                    </div>
                    <span class="text-xs text-gray-500 leading-none">${message.date_sent}</span>
                  `;

                  const avatarContainer = document.createElement('div');
                  avatarContainer.classList.add('flex-shrink-0', 'h-10', 'w-10', 'rounded-full', 'bg-gray-300');

                  messageContainer.appendChild(messageContent);
                  messageContainer.appendChild(avatarContainer);

                  return messageContainer;
            }

            function receivedMessageElement(message) {
              const messageContainer = document.createElement('div');
              messageContainer.classList.add('flex', 'w-full', 'mt-2', 'space-x-3', 'max-w-xs');

              const avatarContainer = document.createElement('div');
              avatarContainer.classList.add('flex-shrink-0', 'h-10', 'w-10', 'rounded-full', 'bg-gray-300');

              const messageContent = document.createElement('div');
              messageContent.innerHTML = `
                <div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">
                  <p class="text-sm">${message}</p>
                </div>
                <span class="text-xs text-gray-500 leading-none">${message.date_sent}</span>
              `;

              messageContainer.appendChild(avatarContainer);
              messageContainer.appendChild(messageContent);

              return messageContainer;
            }



</script>

<div class="flex flex-col items-center justify-center w-screen min-h-screen bg-gray-100 text-gray-800 p-10">
    <div class="flex flex-col flex-grow w-full max-w-xl bg-white shadow-xl rounded-lg overflow-hidden">
        <div class="flex flex-col flex-grow h-0 p-4 overflow-auto" id="chat-window">
            {% for message in context.messages %}
            {% if message.sender_id != current_user.id %}
            <div class="flex w-full mt-2 space-x-3 max-w-xs">
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>
                <div>
                    <div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>
                    <span class="text-xs text-gray-500 leading-none">{{ message.date_sent.strftime("%m %B %Y, %H:%M") }}</span>
                </div>
            </div>
            {% else %}
            <div class="flex w-full mt-2 space-x-3 max-w-xs ml-auto justify-end">
                <div>
                    <div class="bg-blue-600 text-white p-3 rounded-l-lg rounded-br-lg">
                        <p class="text-sm">{{ message.body }}</p>
                    </div>
                    <span class="text-xs text-gray-500 leading-none">{{ message.date_sent.strftime("%m %B %Y, %H:%M") }}</span>
                </div>
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>
            </div>
            {% endif %}
            {% endfor %}
        </div>

        <div class="bg-gray-300 p-4">
            <input class="flex items-center h-10 w-full rounded px-3 text-sm" type="text" id="text"
                   placeholder="Type your message…">
        </div>
    </div>
</div>

</body>
</html>

chat/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="flex justify-center bg-gray-100 py-4">
        <h1 class="text-gray-600 text-4xl font-bold"> Friends</h1>
    </div>
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
            <th scope="col" class="p-4">
                <div class="flex items-center">
                    <input id="checkbox-all-search" type="checkbox"
                           class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="checkbox-all-search" class="sr-only">checkbox</label>
                </div>
            </th>
            <th scope="col" class="px-6 py-3">
                Name
            </th>
            <th scope="col" class="px-6 py-3">
                Status
            </th>
            <th scope="col" class="px-6 py-3">
            </th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="w-4 p-4">
                <div class="flex items-center">
                    <input id="checkbox-table-search-1" type="checkbox"
                           class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
                </div>
            </td>
            <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
                <img class="w-10 h-10 rounded-full" src="..\static\image\default.png"
                     alt="Jese image">
                <div class="pl-3">
                    <div class="text-base font-semibold">{{ user.first_name }} {{ user.last_name }}</div>
                    <div class="font-normal text-gray-500">{{ user.email }}</div>
                </div>
            </th>
            <td class="px-6 py-4">
                <div class="flex items-center">
                    <div class="h-2.5 w-2.5 rounded-full bg-green-500 mr-2"></div>
                    Online
                </div>
            </td>
            <td class="px-6 py-4">
                <a href="{{ url_for('main.message', user_id=user.id) }}">
                    <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800">
                  <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                      Message
                  </span>
                    </button>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

chat/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Title</title>

</head>
<body>
<div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    {% block body %}
    {% endblock %}
</div>

</body>
</html>

chat/templates/signup.html
{% extends "layout.html" %}

{% block body %}


<section class="bg-gray-50">
    <div class="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 class="text-xl font-bold text-center leading-tight tracking-tight text-gray-900 md:text-2xl">
                Create a account
            </h1>
            <form class="space-y-4 md:space-y-6" action="" method="POST">
                {{ form.hidden_tag() }}
                <div class="grid grid-cols-2 gap-2">
                    <div>
                        {{ form.first_name.label(class="block mb-2 text-sm font-medium text-gray-900") }}
                        {{ form.first_name(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm
                        rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5",
                        placeholder="First name") }}
                    </div>
                    <div>
                        {{ form.last_name.label(class="block mb-2 text-sm font-medium text-gray-900") }}
                        {{ form.last_name(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm
                        rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5",
                        placeholder="Last name") }}
                    </div>
                </div>
                <div>
                    {{ form.email.label(class="block mb-2 text-sm font-medium text-gray-900") }}
                    {{ form.email(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm
                    rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5",
                    placeholder="example@email.com") }}
                </div>
                <div class="grid grid-cols-2 gap-2">
                    <div>
                        {{ form.password.label(class="block mb-2 text-sm font-medium text-gray-900") }}
                        {{ form.password(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm
                        rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5",
                        placeholder="*********") }}
                    </div>
                    <div>
                        {{ form.confirm_password.label(class="block mb-2 text-sm font-medium text-gray-900") }}
                        {{ form.confirm_password(class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm
                        rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5",
                        placeholder="*********") }}
                        {% if form.confirm_password.errors %}
                        {% for error in form.password.errors %}
                        {{ error }}
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <button type="submit"
                        class="w-full text-white bg-gray-600 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                    Sign in
                </button>
                <p class="text-sm font-light text-gray-500">
                    Don’t have an account yet? <a href="#"
                                                  class="font-medium text-primary-600 hover:underline">Sign
                    up</a>
                </p>
            </form>
        </div>
    </div>
</section>

{% endblock body %}